# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 887774a3c4836d8210a759f30200545344bee60a6c1eb46a52f95d95461438af0eac841388b029de72af34766a4c452eab9380acab483a34014f99841e550b3d

test:
  secret_key_base: d145ed8de7f66d8d997f7c577907dc48ce395799993d485b529a7b17516174d2fc797313f0e2db0db9121908c9cf2b2fe6ebc553dd22f154213f140819feb89d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
